### ISSUE TITLE
Do you have env files ?

### ISSUE THREAD

**Issue by clementvp** [Bastoon01/majoba#1]
Hi guys, 
For our build automation and deployment we need env files, but you have hardcoded some things like the connection url to the mongo, or the listen ports of the app.
Do you know  [dotenv](https://www.npmjs.com/package/dotenv) ?

**Comment by gabnie** [comment]
Hey,
Alright, we've integrated dotenv in server side. Env file contains only mongodb connection url and node app server port.

Tell us if you need something else.

Have fun!

**Comment by clementvp** [comment]
That's great ;)
